### ISSUE TITLE
fail in run_script.py "'TextCurve' object has no attribute 'align_x'"

### ISSUE THREAD

**Issue by qzhou711** [njanakiev/blender-scripting-intro#3] opened 2019-08-14 11:57 UTC
Hi, I got a failure when run the "run_script.py"

`found bundled python: /home/qiang/zq/blender-2.71-linux-glibc211-x86_64/2.71/python
createSimpleScene called
createLamp called
Traceback (most recent call last):
  File "/home/qiang/zq/git-space/blender-scripting/run_script.py", line 22, in <module>
    exec(compile(open(file).read(), scriptFile, 'exec'))
  File "fisher_iris_visualization.py", line 186, in <module>
    createLabels(X, y, labels, cameraObj)
  File "fisher_iris_visualization.py", line 128, in createLabels
    fontCurve.align_x = 'CENTER'
AttributeError: 'TextCurve' object has no attribute 'align_x'
`
I wonder if there exists a problem about the version of the blender or python. Thanks for your attention.

**Comment by njanakiev** [comment] 2021-09-21 14:56
Thanks for the Issue @bamboosdu. I was not able to reproduce this error for Blender 2.93.4, closing it for now

**Closed as completed** 2021-09-21 14:57 UTC
